### ISSUE TITLE
ci passed on panic

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-spdk-bridge#340]
```
opi-spdk-client_1  | 2023/04/20 19:31:01 Testing NewMiddleendServiceClient
opi-spdk-client_1  | 2023/04/20 19:31:01 =======================================
opi-spdk-client_1  | 2023/04/20 19:31:01 DoFrontend tests failed with error: rpc error: code = Unimplemented desc = unknown service opi_api.storage.v1.MiddleendService
opi-spdk-client_1  | panic: DoFrontend tests failed with error: rpc error: code = Unimplemented desc = unknown service opi_api.storage.v1.MiddleendService
opi-spdk-client_1  | 
opi-spdk-client_1  | goroutine 1 [running]:
opi-spdk-client_1  | log.Panicf({0x9c1984?, 0xc000145c50?}, {0xc000123d00?, 0xc0000bf500?, 0x0?})
opi-spdk-client_1  | 	/usr/local/go/src/log/log.go:391 +0x67
opi-spdk-client_1  | github.com/opiproject/godpu/cmd.NewStorageTestCommand.func1(0xc0001aac00?, {0xc0001762c0?, 0x1?, 0x1?})
opi-spdk-client_1  | 	/app/cmd/storage-test.go:66 +0x37f
opi-spdk-client_1  | github.com/spf13/cobra.(*Command).execute(0xc0001aac00, {0xc000176290, 0x1, 0x1})
opi-spdk-client_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
opi-spdk-client_1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc0001aa000)
opi-spdk-client_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
opi-spdk-client_1  | github.com/spf13/cobra.(*Command).Execute(...)
opi-spdk-client_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
opi-spdk-client_1  | main.main()
opi-spdk-client_1  | 	/app/main.go:17 +0x1e
```
https://github.com/opiproject/opi-spdk-bridge/actions/runs/4758143330/jobs/8455818039?pr=338#step:8:254

**Comment by glimchb** [comment]
fixed
